// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id,createdAt,updatedAt,title,description,publishedAt,url,feedId)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, createdat, updatedat, title, description, publishedat, url, feedid
`

type CreatePostParams struct {
	ID          uuid.UUID
	Createdat   time.Time
	Updatedat   time.Time
	Title       string
	Description sql.NullString
	Publishedat time.Time
	Url         string
	Feedid      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Createdat,
		arg.Updatedat,
		arg.Title,
		arg.Description,
		arg.Publishedat,
		arg.Url,
		arg.Feedid,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Title,
		&i.Description,
		&i.Publishedat,
		&i.Url,
		&i.Feedid,
	)
	return i, err
}
